local opt = vim.opt
opt.inccommand = "split"
opt.smartcase = true
opt.ignorecase = true
opt.nu = true
opt.rnu = true
opt.splitbelow = true
opt.signcolumn = "yes"
opt.shada = { "'10", "<0", "s10", "h" }
opt.swf = false
opt.formatoptions:remove "o"
opt.wrap = true
opt.lbr = true
opt.ts = 4
opt.shiftwidth = 4
opt.more = false
opt.laststatus = 3
vim.opt.gcr = ""
vim.opt.ut = 50
